<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>
            net10.0;net9.0;net8.0;net7.0;net6.0;net5.0;
            netstandard2.1;netstandard2.0;
            net481;
        </TargetFrameworks>
        <LangVersion>latest</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>

        <RootNamespace>ScrubJay.Functional.Tests</RootNamespace>

        <OutputType>Exe</OutputType>
        <AssemblyName>ScrubJay.Functional.Tests</AssemblyName>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="TUnit" Version="0.56.50"/>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\src\ScrubJay.Functional.csproj" />
    </ItemGroup>

</Project>