<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>net10.0;net8.0;</TargetFrameworks>
        <SuppressTfmSupportBuildErrors>true</SuppressTfmSupportBuildErrors>
        <LangVersion>preview</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>

        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>
<!--        <TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport>-->
        <OutputType>Exe</OutputType>
        
        <AssemblyName>ScrubJay.Functional.Tests</AssemblyName>
        <RootNamespace>ScrubJay.Functional.Tests</RootNamespace>
        
        <NoWarn>xUnit1037; CS1718</NoWarn>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.13.0" />
        <PackageReference Include="xunit.v3" Version="2.0.3" />
        <PackageReference Include="xunit.runner.visualstudio" Version="3.1.1" />
    </ItemGroup>

    <!-- Project References -->
    <ItemGroup>
      <ProjectReference Include="..\src\ScrubJay.Functional.csproj" />
    </ItemGroup>
    
    <!-- NuGet Packages -->
    
    <!-- Global Usings -->
    <ItemGroup>
        <Using Include="Xunit"/>
        <Using Include="System.Diagnostics"/>
        <Using Include="System.Diagnostics.CodeAnalysis"/>
    </ItemGroup>
</Project>
