<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <AssemblyName>ScrubJay.Functional.ConsoleApp</AssemblyName>
        <RootNamespace>ScrubJay.Functional.ConsoleApp</RootNamespace>
        
        <TargetFramework>net9.0</TargetFramework>
        <LangVersion>latest</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\src\ScrubJay.Functional.csproj" />
    </ItemGroup>

</Project>
